name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        node-version: [15.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: $

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js $
        uses: actions/setup-node@v1
        with:
          node-version: $.
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
